//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.ENTE.Prod {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:vav", ConfigurationName="ENTE.Prod.ServiceEnteSoap")]
    public interface ServiceEnteSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/ConsultaTimbrado", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string ConsultaTimbrado(string TimParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/ConsultaTimbrado", ReplyAction="*")]
        System.Threading.Tasks.Task<string> ConsultaTimbradoAsync(string TimParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaPago", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InformaPago(string pagParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaPago", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InformaPagoAsync(string pagParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaBoletaDeposito", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InformaBoletaDeposito(string pagParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaBoletaDeposito", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InformaBoletaDepositoAsync(string pagParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaTasa", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string InformaTasa(string pagParametro);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:vav/InformaTasa", ReplyAction="*")]
        System.Threading.Tasks.Task<string> InformaTasaAsync(string pagParametro);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServiceEnteSoapChannel : Gateway.ENTE.Prod.ServiceEnteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceEnteSoapClient : System.ServiceModel.ClientBase<Gateway.ENTE.Prod.ServiceEnteSoap>, Gateway.ENTE.Prod.ServiceEnteSoap {
        
        public ServiceEnteSoapClient() {
        }
        
        public ServiceEnteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceEnteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceEnteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string ConsultaTimbrado(string TimParametro) {
            return base.Channel.ConsultaTimbrado(TimParametro);
        }
        
        public System.Threading.Tasks.Task<string> ConsultaTimbradoAsync(string TimParametro) {
            return base.Channel.ConsultaTimbradoAsync(TimParametro);
        }
        
        public string InformaPago(string pagParametro) {
            return base.Channel.InformaPago(pagParametro);
        }
        
        public System.Threading.Tasks.Task<string> InformaPagoAsync(string pagParametro) {
            return base.Channel.InformaPagoAsync(pagParametro);
        }
        
        public string InformaBoletaDeposito(string pagParametro) {
            return base.Channel.InformaBoletaDeposito(pagParametro);
        }
        
        public System.Threading.Tasks.Task<string> InformaBoletaDepositoAsync(string pagParametro) {
            return base.Channel.InformaBoletaDepositoAsync(pagParametro);
        }
        
        public string InformaTasa(string pagParametro) {
            return base.Channel.InformaTasa(pagParametro);
        }
        
        public System.Threading.Tasks.Task<string> InformaTasaAsync(string pagParametro) {
            return base.Channel.InformaTasaAsync(pagParametro);
        }
    }
}
