//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MetModel : DbContext
    {
        public MetModel()
            : base("name=MetModel")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
        
        public DbSet<OPERACION> OPERACION { get; set; }
        public DbSet<TIPOOPERACION> TIPOOPERACION { get; set; }
        public DbSet<TRANSACCION> TRANSACCION { get; set; }
        public DbSet<REIMPRESIONES> REIMPRESIONES { get; set; }
        public DbSet<ENTIDAD> ENTIDAD { get; set; }
        public DbSet<TIPOENTIDAD> TIPOENTIDAD { get; set; }
        public DbSet<USUARIO> USUARIOS { get; set; }
    }
}
