//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class OPERACION
    {
        public decimal OPERACIONID { get; set; }
        public Nullable<decimal> TIPOOPERACIONID { get; set; }
        public decimal NROTRAMITE { get; set; }
        public Nullable<decimal> NROFORMULARIO { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal USUARIOID { get; set; }
        public short FINALIZADO { get; set; }
        public Nullable<short> SECUENCIA { get; set; }
    
        public virtual TIPOOPERACION TIPOOPERACION { get; set; }
    }
}
