//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAO
{
    using System;
    using System.Collections.Generic;
    
    public partial class TIPOOPERACION
    {
        public TIPOOPERACION()
        {
            this.OPERACION = new HashSet<OPERACION>();
        }
    
        public decimal TIPOOPERACIONID { get; set; }
        public string DESCRIPCION { get; set; }
    
        public virtual ICollection<OPERACION> OPERACION { get; set; }
    }
}
