//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.ENTE {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ENTE.WS_RespuestaEnteSoap")]
    public interface WS_RespuestaEnteSoap {
        
        // CODEGEN: Generating message contract since element name respuesta from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTimbrado", ReplyAction="*")]
        Gateway.ENTE.ConsultaTimbradoResponse ConsultaTimbrado(Gateway.ENTE.ConsultaTimbradoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ConsultaTimbrado", ReplyAction="*")]
        System.Threading.Tasks.Task<Gateway.ENTE.ConsultaTimbradoResponse> ConsultaTimbradoAsync(Gateway.ENTE.ConsultaTimbradoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTimbradoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaTimbrado", Namespace="http://tempuri.org/", Order=0)]
        public Gateway.ENTE.ConsultaTimbradoRequestBody Body;
        
        public ConsultaTimbradoRequest() {
        }
        
        public ConsultaTimbradoRequest(Gateway.ENTE.ConsultaTimbradoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaTimbradoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string respuesta;
        
        public ConsultaTimbradoRequestBody() {
        }
        
        public ConsultaTimbradoRequestBody(string respuesta) {
            this.respuesta = respuesta;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ConsultaTimbradoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ConsultaTimbradoResponse", Namespace="http://tempuri.org/", Order=0)]
        public Gateway.ENTE.ConsultaTimbradoResponseBody Body;
        
        public ConsultaTimbradoResponse() {
        }
        
        public ConsultaTimbradoResponse(Gateway.ENTE.ConsultaTimbradoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ConsultaTimbradoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ConsultaTimbradoResult;
        
        public ConsultaTimbradoResponseBody() {
        }
        
        public ConsultaTimbradoResponseBody(string ConsultaTimbradoResult) {
            this.ConsultaTimbradoResult = ConsultaTimbradoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WS_RespuestaEnteSoapChannel : Gateway.ENTE.WS_RespuestaEnteSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WS_RespuestaEnteSoapClient : System.ServiceModel.ClientBase<Gateway.ENTE.WS_RespuestaEnteSoap>, Gateway.ENTE.WS_RespuestaEnteSoap {
        
        public WS_RespuestaEnteSoapClient() {
        }
        
        public WS_RespuestaEnteSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WS_RespuestaEnteSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_RespuestaEnteSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WS_RespuestaEnteSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Gateway.ENTE.ConsultaTimbradoResponse Gateway.ENTE.WS_RespuestaEnteSoap.ConsultaTimbrado(Gateway.ENTE.ConsultaTimbradoRequest request) {
            return base.Channel.ConsultaTimbrado(request);
        }
        
        public string ConsultaTimbrado(string respuesta) {
            Gateway.ENTE.ConsultaTimbradoRequest inValue = new Gateway.ENTE.ConsultaTimbradoRequest();
            inValue.Body = new Gateway.ENTE.ConsultaTimbradoRequestBody();
            inValue.Body.respuesta = respuesta;
            Gateway.ENTE.ConsultaTimbradoResponse retVal = ((Gateway.ENTE.WS_RespuestaEnteSoap)(this)).ConsultaTimbrado(inValue);
            return retVal.Body.ConsultaTimbradoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Gateway.ENTE.ConsultaTimbradoResponse> Gateway.ENTE.WS_RespuestaEnteSoap.ConsultaTimbradoAsync(Gateway.ENTE.ConsultaTimbradoRequest request) {
            return base.Channel.ConsultaTimbradoAsync(request);
        }
        
        public System.Threading.Tasks.Task<Gateway.ENTE.ConsultaTimbradoResponse> ConsultaTimbradoAsync(string respuesta) {
            Gateway.ENTE.ConsultaTimbradoRequest inValue = new Gateway.ENTE.ConsultaTimbradoRequest();
            inValue.Body = new Gateway.ENTE.ConsultaTimbradoRequestBody();
            inValue.Body.respuesta = respuesta;
            return ((Gateway.ENTE.WS_RespuestaEnteSoap)(this)).ConsultaTimbradoAsync(inValue);
        }
    }
}
