//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gateway.TramiteService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TramiteService.TramiteService")]
    public interface TramiteService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TramiteService/Clasificar", ReplyAction="http://tempuri.org/TramiteService/ClasificarResponse")]
        void Clasificar(string codigoBarra);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/TramiteService/Clasificar", ReplyAction="http://tempuri.org/TramiteService/ClasificarResponse")]
        System.Threading.Tasks.Task ClasificarAsync(string codigoBarra);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TramiteServiceChannel : Gateway.TramiteService.TramiteService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TramiteServiceClient : System.ServiceModel.ClientBase<Gateway.TramiteService.TramiteService>, Gateway.TramiteService.TramiteService {
        
        public TramiteServiceClient() {
        }
        
        public TramiteServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TramiteServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TramiteServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TramiteServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void Clasificar(string codigoBarra) {
            base.Channel.Clasificar(codigoBarra);
        }
        
        public System.Threading.Tasks.Task ClasificarAsync(string codigoBarra) {
            return base.Channel.ClasificarAsync(codigoBarra);
        }
    }
}
